import type { Metadata } from 'next';
import dynamic from 'next/dynamic';

import '@/style/globals.css';

const NostrContext = dynamic(() => import('@/context/nostr').then((mod) => mod.NostrContext), {
  loading: () => (
    <div className='flex justify-center items-center w-full h-full'>
      <p className='font-bold'>Loading...</p>
    </div>
  ),
  ssr: false,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`antialiased`}>
        <NostrContext>{children}</NostrContext>
      </body>
    </html>
  );
}
